### ISSUE TITLE
 Re-calculation issue of Calculated Clock Frequency 

### ISSUE THREAD

**Issue by ytsnew** [Microchip-MPLAB-Harmony/bsp#4] opened 2020-06-28 00:05 UTC
Please visit https://www.microchip.com/forums/m1137705.aspx .

yts

**Comment by vishalnxt** [comment] 2021-01-25 06:58
This is by design. Going forward, we may consider adding this feature.

**Comment by vishalnxt** [comment] 2021-01-25 06:58
Closing the ticket for now.

**Closed as completed by vishalnxt** 2021-01-25 06:58 UTC
